parameters:
#    frontend.example.class: Ganguera\FrontendBundle\Example

services:
    ganguera.utilidades:
        class: Ganguera\FrontendBundle\Util\Util
        
    login_listener:
        arguments: [@router]
        class: Ganguera\FrontendBundle\Listener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
            
    ganguera.servicio_web:
        arguments: [@doctrine.orm.entity_manager]
        class: Ganguera\FrontendBundle\ServicioWeb\Servicio