backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /bckadmin

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

#
## Servicios Web ##
#
frontend_webservices:
    pattern:  /websryan
    defaults: { _controller: FrontendBundle:Default:servicio }

frontend_client_webservice:
    pattern:  /consumir/websryan
    defaults: { _controller: FrontendBundle:Default:clientServicio }